### PR TITLE
Final touches

### PR DESCRIPTION
**Pull request by ms-np**
add README
finalise Dev strategy
update Index file as per validator issues
update CSS file as per validator issues
update the wireframe

### CODE REVIEW

**Review by aleks2407 — CHANGES_REQUESTED** [review]
Looks good to me! You did a great job) there are few moments that still should be adjusted though. 
1. I didn't add the css rule to float the main section, as a result the sidebar is located wrongly. 
and 2. the "home" button in navbar leads to your profile. Could you check pls?

**Comment by ms-np** [comment]
I've made the requested changes. shall i merge&confirm PR? Or it's still on your side to review and merge?

**Comment by ms-np** [comment]
Merging as is, no width changes after several unsuccessful attempts

**Comment by snicoll** [comment]
Well done. Great way of collaborating and using GitHub features.

**Pull request merged**
